spring:
  application:
    name: pedidos
  datasource:
    url: jdbc:postgresql://localhost:5555/icompraspedidos
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

icompras:
  pedidos:
    clients:
      produtos:
        url: 'http://localhost:8081/produtos'
      clientes:
        url: 'http://localhost:8082/clientes'

